
# restore_model: ''
restore_model: ./checkpoints/exp_fp_adv/states_500000.pth
# restore_model: ./checkpoints/exp_fp_adv/states.pth

log_dir: logs/exp_fp_adv
checkpoint_dir: checkpoints/exp_fp_adv

# dataset
train_wavs_path: C:/Users/20220020/Desktop/TTS GP/jordanian_tts_data/wav_new
train_labels: C:/Users/20220020/Desktop/TTS GP/jordanian_tts_data/processed/train_phon.txt

test_wavs_path: C:/Users/20220020/Desktop/TTS GP/jordanian_tts_data/wav_new
test_labels: C:/Users/20220020/Desktop/TTS GP/jordanian_tts_data/processed/test_phon.txt

label_pattern: '"(?P<filename>.*)" "(?P<phonemes>.*)"'

# for fastpitch
f0_dict_path: C:/Users/20220020/Desktop/TTS GP/jordanian_tts_data/processed/pitch_dict.pt

f0_mean: 177.57214
f0_std: 64.56166

# loss weights
gan_loss_weight: 2.
feat_loss_weight: 1.

# batch sizes
max_lengths: [1000, 1300, 1850, 30000] # 1 frame ≈ 11.6ms
batch_sizes: [16, 12, 8, 4]

# optimizers
g_lr: 1.0e-5    # lr for AdamW optimizer (generator)
g_beta1: 0.     # beta1 for AdamW optimizer (generator)
g_beta2: 0.99   # beta2 for AdamW optimizer (generator)

d_lr: 1.0e-5   # lr for AdamW optimizer (discriminator)
d_beta1: 0.     # beta1 for AdamW optimizer (discriminator)
d_beta2: 0.99   # beta2 for AdamW optimizer (discriminator)

n_save_states_iter: 1000
n_save_backup_iter: 50000

epochs: 10000
